apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-database
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SteveHoareau18/Master-M2-FullStack.git
    targetRevision: HEAD
    path: TD-Jour6/k8s/statefulsets
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates