apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudshop-frontend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SteveHoareau18/Master-M2-FullStack.git
    targetRevision: HEAD
    path: TD-Jour6
    directory:
      include: '{deployments/frontend.yaml,ingress}/**/*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudshop-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true